# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"
reviews:
  auto_review:
    enabled: true
    drafts: false
  path_filters:
    - "!dist/**"
    - "!node_modules/**"
    - "!.next/**"
    - "!*.lock"
  tools:
    eslint:
      enabled: true
    biome:
      enabled: true
